group 'com.jolibox.android.sdk.ads.flutter'
version '0.3.0'

buildscript {
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:8.2.2'
    }
}

apply plugin: 'com.android.library'

def joliboxAdsVersion = project.findProperty('joliboxAdsVersion') ?: '1.9.0-rc.22399'

android {
    namespace 'com.jolibox.android.sdk.ads.flutter'
    compileSdk 34

    defaultConfig {
        minSdk 23
    }
}

dependencies {
    implementation "com.jolibox.android:jolibox-platform-sdk-all:$joliboxAdsVersion"
}
