group 'com.jolibox.android.sdk.ads.flutter'
version '0.4.0'

buildscript {
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:8.2.2'
    }
}

apply plugin: 'com.android.library'

repositories {
    google()
    mavenCentral()
    maven { url 'https://repo.jolibox.com/repository/public/' }
    maven { url 'https://repo.jolibox.com/repository/android-internal/' }
}

def joliboxAdsVersion = project.findProperty('joliboxAdsVersion') ?: '1.9.0-rc.23239'

android {
    namespace 'com.jolibox.android.sdk.ads.flutter'
    compileSdk 35

    defaultConfig {
        minSdk 23
    }
}

dependencies {
    implementation "com.jolibox.android:jolibox-platform-sdk-all:$joliboxAdsVersion"
}
